version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: $dockerfile
    volumes:
      - $hostdir:/host_dir
    container_name: my_custom_container_name
    image: my_custom_image_name:latest
    command: $command
